//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Praktika1
{
    using System;
    using System.Collections.Generic;
    
    public partial class objects
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public objects()
        {
            this.supplies = new HashSet<supplies>();
        }
    
        public int Id { get; set; }
        public int Type_id { get; set; }
        public string Address_City { get; set; }
        public string Address_Street { get; set; }
        public string Address_Hose { get; set; }
        public string Address_Number { get; set; }
        public Nullable<int> Coordinate_latitude { get; set; }
        public Nullable<int> Coordinate_longitude { get; set; }
        public Nullable<int> TotalFloors { get; set; }
        public Nullable<decimal> TotalArea { get; set; }
        public Nullable<int> Rooms { get; set; }
    
        public virtual type_objects type_objects { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<supplies> supplies { get; set; }
    }
}
